services:
  postgres:
    image: postgres:16
    container_name: rede-social-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: rede_social
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./scripts/db:/docker-entrypoint-initdb.d

volumes:
  pg_data:
